//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROHV.Core.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsumerHabReviewIssueState
    {
        public System.Guid Id { get; set; }
        public Nullable<int> ConsumerHabReviewId { get; set; }
        public Nullable<int> ValuedOutcomesState { get; set; }
        public Nullable<int> CommunityHabilitationPlanState { get; set; }
        public Nullable<int> IndividualsSatisfactionState { get; set; }
        public Nullable<int> AdvocatesSatisfactionState { get; set; }
        public Nullable<int> SignificantChangesState { get; set; }
        public Nullable<int> SignificantHealthState { get; set; }
        public Nullable<int> SafeguardChangeState { get; set; }
    
        public virtual ConsumerHabReview ConsumerHabReview { get; set; }
    }
}
