//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROHV.Core.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsumerDetailOld
    {
        public Nullable<short> AnnualUnits { get; set; }
        public bool Billable { get; set; }
        public int ConsumerDetailID { get; set; }
        public Nullable<int> CunsumerID { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public string LocCode { get; set; }
        public string PriceID { get; set; }
        public Nullable<int> ProgramID { get; set; }
        public Nullable<System.DateTime> RayimDate { get; set; }
        public string Unit_Quantity { get; set; }
        public string Provider { get; set; }
    }
}
