//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROHV.Core.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsumerTherapy
    {
        public int ConsumerTherapyId { get; set; }
        public Nullable<int> ConsumerId { get; set; }
        public Nullable<int> TherapyId { get; set; }
        public string NoOfTimes { get; set; }
        public Nullable<int> Frequency { get; set; }
        public string Provider { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
    
        public virtual Consumer Consumer { get; set; }
        public virtual List List { get; set; }
    }
}
