//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROHV.Core.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsumerPrintDocumentValuedOutcome
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ConsumerPrintDocumentValuedOutcome()
        {
            this.ConsumerPrintDocumentVOServeActions = new HashSet<ConsumerPrintDocumentVOServeAction>();
        }
    
        public int Id { get; set; }
        public Nullable<int> PrintDocumentId { get; set; }
        public string ValuedOutcome { get; set; }
    
        public virtual ConsumerPrintDocument ConsumerPrintDocument { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsumerPrintDocumentVOServeAction> ConsumerPrintDocumentVOServeActions { get; set; }
    }
}
