//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROHV.Core.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsumerPrintDocument
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ConsumerPrintDocument()
        {
            this.ConsumerPrintDocumentValuedOutcomes = new HashSet<ConsumerPrintDocumentValuedOutcome>();
        }
    
        public int Id { get; set; }
        public int ContactId { get; set; }
        public int StatusId { get; set; }
        public int ConsumerId { get; set; }
        public int AddedById { get; set; }
        public Nullable<int> UpdatedById { get; set; }
        public string ServiceAction1 { get; set; }
        public string ServiceAction2 { get; set; }
        public string ServiceAction3 { get; set; }
        public string ServiceAction4 { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<int> ServiceTypeId { get; set; }
        public string ServiceTypeTitle { get; set; }
    
        public virtual SystemUser SystemUser { get; set; }
        public virtual Consumer Consumer { get; set; }
        public virtual Contact Contact { get; set; }
        public virtual DocumentPrintStatus DocumentPrintStatus { get; set; }
        public virtual SystemUser SystemUser1 { get; set; }
        public virtual ServiceType ServiceType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsumerPrintDocumentValuedOutcome> ConsumerPrintDocumentValuedOutcomes { get; set; }
    }
}
