//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROHV.Core.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsumerHabPlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ConsumerHabPlan()
        {
            this.ConsumerHabPlanSafeguards = new HashSet<ConsumerHabPlanSafeguard>();
            this.ConsumerHabPlanValuedOutcomes = new HashSet<ConsumerHabPlanValuedOutcome>();
        }
    
        public int ConsumerHabPlanId { get; set; }
        public int ConsumerId { get; set; }
        public int HabServiceId { get; set; }
        public int CoordinatorId { get; set; }
        public int FrequencyId { get; set; }
        public int DurationId { get; set; }
        public int StatusId { get; set; }
        public int AddedById { get; set; }
        public Nullable<int> UpdatedById { get; set; }
        public string Name { get; set; }
        public string QMRP { get; set; }
        public System.DateTime EnrolmentDate { get; set; }
        public System.DateTime DatePlan { get; set; }
        public System.DateTime EffectivePlan { get; set; }
        public bool IsAproved { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public Nullable<System.DateTime> SignatureDate { get; set; }
        public bool IsAutoSignature { get; set; }
    
        public virtual ConsumerHabPlanDuration ConsumerHabPlanDuration { get; set; }
        public virtual ConsumerHabPlanFrequency ConsumerHabPlanFrequency { get; set; }
        public virtual ConsumerHabPlanStatus ConsumerHabPlanStatus { get; set; }
        public virtual Consumer Consumer { get; set; }
        public virtual Contact Contact { get; set; }
        public virtual ServicesList ServicesList { get; set; }
        public virtual SystemUser SystemUser { get; set; }
        public virtual SystemUser SystemUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsumerHabPlanSafeguard> ConsumerHabPlanSafeguards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsumerHabPlanValuedOutcome> ConsumerHabPlanValuedOutcomes { get; set; }
    }
}
