//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROHV.Core.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsumerHabPlanSafeguard
    {
        public int ConsumerHabPlanSafeguardId { get; set; }
        public Nullable<int> ConsumerHabPlanId { get; set; }
        public string Item { get; set; }
        public string Action { get; set; }
        public bool IsIPOP { get; set; }
    
        public virtual ConsumerHabPlan ConsumerHabPlan { get; set; }
    }
}
