//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROHV.Core.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consumer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Consumer()
        {
            this.CaseStatus = new HashSet<CaseStatu>();
            this.ConsumerContactCalls = new HashSet<ConsumerContactCall>();
            this.ConsumerHabPlans = new HashSet<ConsumerHabPlan>();
            this.ConsumerNotificationSettings = new HashSet<ConsumerNotificationSetting>();
            this.ConsumerPhones = new HashSet<ConsumerPhone>();
            this.ConsumerPrintDocuments = new HashSet<ConsumerPrintDocument>();
            this.ConsumerTherapies = new HashSet<ConsumerTherapy>();
            this.EmployeeDocuments = new HashSet<EmployeeDocument>();
            this.ConsumerEmployees = new HashSet<ConsumerEmployee>();
            this.ConsumerNotes = new HashSet<ConsumerNote>();
            this.ConsumerHabReviews = new HashSet<ConsumerHabReview>();
            this.ConsumerServiceCoordinators = new HashSet<ConsumerServiceCoordinator>();
            this.ConsumerAddresses = new HashSet<ConsumerAddress>();
            this.Audits = new HashSet<Audit>();
            this.ConsumerMedicaidNumbers = new HashSet<ConsumerMedicaidNumber>();
        }
    
        public int ConsumerId { get; set; }
        public string FirstName { get; set; }
        public string MI { get; set; }
        public string LastName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string ParentName { get; set; }
        public string ParentAddress1 { get; set; }
        public string ParentAddress2 { get; set; }
        public string ParentCity { get; set; }
        public string ParentState { get; set; }
        public string ParentZip { get; set; }
        public string OtherAddress { get; set; }
        public string OtherName { get; set; }
        public string OtherAddress1 { get; set; }
        public string OtherAddress2 { get; set; }
        public string OtherCity { get; set; }
        public string OtherState { get; set; }
        public string OtherZip { get; set; }
        public string ProviderName { get; set; }
        public Nullable<int> Status { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string MedicaidNo { get; set; }
        public string SocialSecurityNo { get; set; }
        public Nullable<int> PrimaryDiagnosis { get; set; }
        public Nullable<int> SecondaryDiagnosis { get; set; }
        public string TABSNo { get; set; }
        public Nullable<bool> HasServiceCoordinator { get; set; }
        public string AgencyName { get; set; }
        public string ServiceCoordinator { get; set; }
        public Nullable<System.DateTime> LastHIPPA { get; set; }
        public Nullable<System.DateTime> LastConsents { get; set; }
        public Nullable<System.DateTime> LastISP { get; set; }
        public Nullable<System.DateTime> LasyPsycological { get; set; }
        public Nullable<System.DateTime> LastSocial { get; set; }
        public Nullable<System.DateTime> WaiverNODDate { get; set; }
        public Nullable<System.DateTime> MscNODDate { get; set; }
        public Nullable<System.DateTime> LOCDate { get; set; }
        public Nullable<System.DateTime> LastMedical { get; set; }
        public Nullable<int> DayProgramId { get; set; }
        public string DayProgramName { get; set; }
        public string DayProgramAddress1 { get; set; }
        public string DayProgramAddress2 { get; set; }
        public string DayProgramCity { get; set; }
        public string DayProgramState { get; set; }
        public string DayProgramZip { get; set; }
        public string DayProgramContact { get; set; }
        public string County { get; set; }
        public string Cc2 { get; set; }
        public Nullable<int> AgencyNameId { get; set; }
        public Nullable<int> ServiceCoordinatorId { get; set; }
        public Nullable<int> MaxHoursPerWeek { get; set; }
        public Nullable<int> MaxHoursPerYear { get; set; }
        public string RateNote { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<int> MSCId { get; set; }
        public Nullable<int> DHCoordinatorId { get; set; }
        public Nullable<int> CHCoordinatorId { get; set; }
        public Nullable<int> AdvocateId { get; set; }
        public Nullable<int> AdvocatePaperId { get; set; }
    
        public virtual Agency Agency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CaseStatu> CaseStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsumerContactCall> ConsumerContactCalls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsumerHabPlan> ConsumerHabPlans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsumerNotificationSetting> ConsumerNotificationSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsumerPhone> ConsumerPhones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsumerPrintDocument> ConsumerPrintDocuments { get; set; }
        public virtual Contact Contact { get; set; }
        public virtual Contact Contact1 { get; set; }
        public virtual Contact Contact2 { get; set; }
        public virtual Contact Contact3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsumerTherapy> ConsumerTherapies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeDocument> EmployeeDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsumerEmployee> ConsumerEmployees { get; set; }
        public virtual Contact Contact4 { get; set; }
        public virtual Contact Contact11 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsumerNote> ConsumerNotes { get; set; }
        public virtual List List { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsumerHabReview> ConsumerHabReviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsumerServiceCoordinator> ConsumerServiceCoordinators { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsumerAddress> ConsumerAddresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Audit> Audits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsumerMedicaidNumber> ConsumerMedicaidNumbers { get; set; }
    }
}
