//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROHV.Core.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsumerPrintDocumentVOServeAction
    {
        public int Id { get; set; }
        public int PrintDocumentValuedOutcomeId { get; set; }
        public string ServeAndAction { get; set; }
    
        public virtual ConsumerPrintDocumentValuedOutcome ConsumerPrintDocumentValuedOutcome { get; set; }
    }
}
