//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROHV.Core.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDocument
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmployeeDocument()
        {
            this.EmployeeDocumentNotes = new HashSet<EmployeeDocumentNote>();
        }
    
        public int EmployeeDocumentId { get; set; }
        public int ConsumerId { get; set; }
        public int DocumentTypeId { get; set; }
        public int DocumentStatusId { get; set; }
        public int EmployeeId { get; set; }
        public int AddedById { get; set; }
        public Nullable<int> UpdatedById { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public string DocumentPath { get; set; }
        public string DocumentContentType { get; set; }
        public Nullable<System.DateTime> DateDocument { get; set; }
    
        public virtual Consumer Consumer { get; set; }
        public virtual Contact Contact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeDocumentNote> EmployeeDocumentNotes { get; set; }
        public virtual EmployeeDocumentStatus EmployeeDocumentStatus { get; set; }
        public virtual EmployeeDocumentType EmployeeDocumentType { get; set; }
        public virtual SystemUser SystemUser { get; set; }
        public virtual SystemUser SystemUser1 { get; set; }
        public virtual EmployeeDocument EmployeeDocuments1 { get; set; }
        public virtual EmployeeDocument EmployeeDocument1 { get; set; }
    }
}
