//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROHV.Core.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDocumentNote
    {
        public int EmployeeDocumentNoteId { get; set; }
        public int DocumentId { get; set; }
        public int AddedById { get; set; }
        public string Note { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual EmployeeDocument EmployeeDocument { get; set; }
        public virtual SystemUser SystemUser { get; set; }
    }
}
