//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROHV.Core.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class vTimeSheetData
    {
        public string ServiceType { get; set; }
        public string Service { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<System.DateTime> ExportDate { get; set; }
        public int TimeDetailID { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> StopTime { get; set; }
        public Nullable<System.DateTime> Date1 { get; set; }
        public Nullable<decimal> Units { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public string FileNumber { get; set; }
        public int TimeID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<decimal> SessionDuration { get; set; }
    }
}
